# Default values for express-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: NodePort
  gateway:
    name: gateway
    port: 80
    nodePort: 31313
  admin:
    name: admin
    port: 9876
    nodePort: 31314
ingress:
  enabled: false
  # Used to create an Ingress record.
  hosts:
    - express-gateway.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources: {}
config:
  # YAML configuration for the gateway
  gateway:
    # http:
    #   host: '*'
    #   port: 8080
    # admin:
    #   host: '0.0.0.0'
    #   port: 9876
    # apiEndpoints:
    #   api:
    #     host: '*'
    #     paths: '/ip'
    # serviceEndpoints:
    #   httpbin:
    #     url: 'https://httpbin.org'
    # policies:
    #   - jwt
    #   - oauth2
    #   - proxy
    # pipelines:
    #   - name: default
    #     apiEndpoints:
    #       - api
    #     policies:
    #      # - jwt:
    #      #     - action:
    #      #         checkCredentialExistence: false
    #      #         secretOrPublicKeyFile: '/app/key.pem'
    #       - proxy:
    #           - action:
    #               serviceEndpoint: httpbin 
    #               changeOrigin: true
  # YAML configuration for the system
  system:
    # db:
    #   redis:
    #     emulate: true
    #     namespace: EG-
    # crypto:
    #   cipherKey: sensitiveKey
    #   algorithm: aes256
    #   saltRounds: 10
    # session:
    #   secret: keyboard cat
    #   resave: false
    #   saveUninitialized: false
    # accessTokens:
    #   timeToExpiry: 7200000
    # refreshTokens:
    #   timeToExpiry: 7200000
    # authorizationCodes:
    #   timeToExpiry: 7200000

