apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "express-gateway.fullname" . }}
  labels:
    app: {{ template "express-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  gateway.config.yml: |
{{ toYaml .Values.config.gateway | indent 4 }}
  system.config.yml: |
{{ toYaml .Values.config.system | indent 4 }}