apiVersion: v1
kind: Service
metadata:
  name: {{ template "express-gateway.fullname" . }}
  labels:
    app: {{ template "express-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "express-gateway.name" . }}
    release: {{ .Release.Name }}
  type: NodePort
  ports:
    - name: {{ quote .Values.service.gateway.name }}
      port: {{ .Values.service.gateway.port }}
      targetPort: 'gateway'
      nodePort: {{ .Values.service.gateway.nodePort }}
      protocol: TCP
    - name: {{ quote  .Values.service.admin.name }}
      port: {{ .Values.service.admin.port }}
      targetPort: 'admin'
      nodePort: {{ .Values.service.admin.nodePort }}
      protocol: TCP
